name: TFLint on PR
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: latest
          #github_token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
          tflint_wrapper: false
          
