name: TFsec on PR
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: tfsec commenter
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}